Feature/angular UI
kuderluka/notes_laravel pull request #69
Opened 2024-02-25 21:54 UTC by kuderluka

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/login/login.component.html
> +    </div>
This input can be created as a new component

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/login/login.component.html
> +    </div>
This input can be created as a new component

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/login/login.component.ts
> +      password: ['']
Form controls are missing validators

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/login/login.component.ts
> +  constructor(private service: AuthService,private eventService: EventService, private formBuilder: FormBuilder, private router: Router) {}
"service" should be named "authService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/login/login.component.ts
> +      this.service.logout();
Why does "logout()" need to be called here?

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/login/login.component.ts
> +      this.eventService.logout();
Why does "logout()" need to be called here?

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/register/register.component.html
Inputs can be created as components

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/register/register.component.ts
> +  constructor(private formBuilder: FormBuilder, private service: AuthService, private eventService: EventService, private router: Router) {}
"service" should be named "authService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/register/register.component.ts
> +    this.registerForm = this.formBuilder.group({
Form controlls are missing validators

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/register/register.component.ts
> +    this.service.logout();
Why does "logout()" need to be called here?

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/register/register.component.ts
> +    this.eventService.logout();
Why does "logout()" need to be called here?

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/login/login.component.ts
> +  login() {
No documentation

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/auth/register/register.component.ts
> +  register() {
No documentation

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/categories/category-form/category-form.component.ts
> +  constructor(private formBuilder: FormBuilder, private service: NotesService, private router: Router) { }
"service" should be named "notesService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/categories/category-form/category-form.component.ts
> +    if (this.form.invalid) {
User should not be allowed to submit the form if form is invalid. Add a check to "Create category" button, and make the button disabled, if it is invalid.

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/events/event-details/event-details.component.ts
> +  constructor(private route: ActivatedRoute, private service: EventService) {}
"service" should be named "eventService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/events/event-list/event-list.component.html
> +                            <td>{{ event.ticketPrice }}</td>
Event data should be displayed as a single component

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/events/event-list/event-list.component.ts
> +    constructor(private service: EventService) {}
"service" should be named "eventService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/landing/landing.component.ts
> +  constructor(private service: AuthService) {
"service" should be named "authService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/notes/note-destroy/note-destroy.component.ts
> +    this.noteService.deleteNote(this.id).then(() => {
This can be called directly from the list view, it does not need to be its own component. Doing it this way just adds an extra unneeded redirect.

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/notes/note-form/note-form.component.ts
> +  constructor(private route: ActivatedRoute, private formBuilder: FormBuilder, private service: NotesService, private router: Router) { }
"service" should be named "notesService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/notes/note-form/note-form.component.ts
> +  validateDeadline(control: any) {
No documentation

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/notes/note-form/note-form.component.ts
> +    if (this.form.invalid) {
User should not be allowed to submit the form if form is invalid. Add a check to "Create category" button, and make the button disabled, if it is invalid.

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/public/public.component.html
> +                            <td>{{ note.tags }}</td>
Note data should be displayed as a single component

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/public/public.component.ts
> +  constructor(private service:NotesService) {}
"service" should be named "notesService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/public/public.component.ts
Functions are missing documentation

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/notes/note-list/note-list.component.html
> +            <td>{{ note.tags }}</td>
Note data should be displayed as a single component

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/notes/note-list/note-list.component.ts
> +    constructor(private service:NotesService) {}
"service" should be named "notesService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/subcomponents/attend-button/attend-button.component.ts
Functions are missing documentation

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/subcomponents/edit-buttons/edit-buttons.component.html
> +<button class="btn btn-danger" [routerLink]="['/note/destroy', note.id]"> Delete </button>
Instead of redirecting to "/note/destroy" you can create a function "destroy()", that accepts "note.id" as parameter, that deletes it directly.

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/user/user-details/user-details.component.html
> +                            <td>{{ note.tags }}</td>
Note data should be displayed as a single component

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/user/user-details/user-details.component.html
> +                            <td>{{ event.ticketPrice }}</td>
Event data should be displayed as a single component

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/user/user-details/user-details.component.ts
> +    constructor(private route: ActivatedRoute, private service: NotesService) {
"service" should be named "noteService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/components/user/user-list/user-list.component.ts
> +  constructor(private service:NotesService) {
"service" should be named "notesService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/navigation/navigation.component.ts
> +  constructor(private service: AuthService, private router: Router) {}
"service" should be named "authService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/services/auth.service.ts
> +  }
This can be implemented with [interceptors](https://medium.com/@jaydeepvpatil225/http-interceptors-in-angular-6e9891ae0538)

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/services/event.service.ts
> +  }
This can be implemented with [interceptors](https://medium.com/@jaydeepvpatil225/http-interceptors-in-angular-6e9891ae0538)

2024-03-11 18:42 UTC, kristjansuligoj commented on client/src/app/services/notes.service.ts
> +  constructor(private http: HttpClient, private auth: AuthService, private eventService: EventService) { }
"service" should be named "authService", so it is more intuitive

2024-03-11 18:42 UTC, kristjansuligoj commented on routes/api.php
Routes can be simplified with [prefixes](https://tuanburah.medium.com/laravel-api-routes-with-prefix-859d97cbfd49)

2024-03-13 08:05 UTC, vojkovoga requested changes

2024-03-19 19:33 UTC, merged